
CREATE TABLE continents (
    continent_code varchar(20) PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- creating table of countries
CREATE TABLE countries (
    country_code varchar(20) PRIMARY KEY,
    continent_code varchar(20),
    name VARCHAR(255) NOT NULL,
    capital VARCHAR(255),
    FOREIGN KEY (continent_code) REFERENCES continents(continent_code)
);

-- creating table of states
CREATE TABLE states (
    state_id varchar(20) PRIMARY KEY,
    country_code varchar(20),
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (country_code) REFERENCES countries(country_code)
);

-- creating table of cities
CREATE TABLE cities (
    city_id varchar(20) PRIMARY KEY,
    state_id varchar(20),
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (state_id) REFERENCES states(state_id)
);

-- afganistan

INSERT INTO countries VALUES 
("AF", "AS", "Afghanistan", "Kabul");

INSERT INTO states VALUES
("AF-BDS", "AF", "Badakhshan"),
("AF-BDG", "AF", "Badghis"),
("AF-BGL", "AF", "Baghlan"),
("AF-BAL", "AF", "Balkh"),
("AF-BAM", "AF", "Bamyan"),
("AF-DAY", "AF", "Daykundi"),
("AF-FRA", "AF", "Farah"),
("AF-FYB", "AF", "Faryab"),
("AF-GHA", "AF", "Ghazni"),
("AF-GHO", "AF", "Ghor"),
("AF-HEL", "AF", "Helmand"),
("AF-HER", "AF", "Herat"),
("AF-JOW", "AF", "Jowzjan"),
("AF-KAB", "AF", "Kabul"),
("AF-KAN", "AF", "Kandahar"),
("AF-KAP", "AF", "Kapisa"),
("AF-KHO", "AF", "Khost"),
("AF-KNR", "AF", "Kunar"),
("AF-KDZ", "AF", "Kunduz"),
("AF-LAG", "AF", "Laghman"),
("AF-LOG", "AF", "Logar"),
("AF-NAN", "AF", "Nangarhar"),
("AF-NIM", "AF", "Nimroz"),
("AF-NUR", "AF", "Nuristan"),
("AF-PAN", "AF", "Paktia"),
("AF-PAR", "AF", "Paktika"),
("AF-PAN", "AF", "Panjshir"),
("AF-SAM", "AF", "Samangan"),
("AF-SAR", "AF", "Sar-e Pol"),
("AF-TAK", "AF", "Takhar"),
("AF-URU", "AF", "Urozgan"),
("AF-WAR", "AF", "Wardak"),
("AF-ZAB", "AF", "Zabul");

INSERT INTO cities VALUES
("AF-KBL", "AF-KAB", "Kabul"),
("AF-HEA", "AF-HEL", "Lashkargah"),
("AF-MZR", "AF-BAL", "Mazar-i-Sharif"),
("AF-KDH", "AF-KAN", "Kandahar"),
("AF-JAA", "AF-JOW", "Jalalabad"),
("AF-BAH", "AF-BAM", "Bamyan"),
("AF-GZR", "AF-GHA", "Ghazni"),
("AF-KNR", "AF-KNR", "Kunar"),
("AF-TIA", "AF-TAK", "Taloqan"),
("AF-PKA", "AF-PAN", "Pul-e-Alam"),
("AF-FAI", "AF-FRA", "Farah"),
("AF-ASD", "AF-ASD", "Asadabad"),
("AF-MOZ", "AF-MOZ", "Maimana"),
("AF-KRZ", "AF-KRZ", "Kunduz"),
("AF-GHA", "AF-GHA", "Ghazni"),
("AF-SHI", "AF-SHI", "Shibirghan"),
("AF-PUL", "AF-PUL", "Puli Khumri"),
("AF-GTI", "AF-GTI", "Gardez"),
("AF-AYB", "AF-FYB", "Maymana"),
("AF-BAG", "AF-BAG", "Baghlan"),
("AF-TAL", "AF-TAL", "Taloqan"),
("AF-ZAR", "AF-ZAR", "Zaranj"),
("AF-SNJ", "AF-SNJ", "Saranj"),
("AF-KSF", "AF-KSF", "Khost"),
("AF-GOZ", "AF-GOZ", "Ghazni"),
("AF-PAK", "AF-PAK", "Paktia"),
("AF-ALB", "AF-ALB", "Asadabad"),
("AF-BAZ", "AF-BAZ", "Bazarak"),
("AF-BAG", "AF-BAG", "Baghlan"),
("AF-BAN", "AF-BAN", "Bannu"),
("AF-BAR", "AF-BAR", "Baraki Barak"),
("AF-BAT", "AF-BAT", "Batikot"),
("AF-BUK", "AF-BUK", "Bukhara"),
("AF-CHI", "AF-CHI", "Chishti Sharif"),
("AF-DAI", "AF-DAI", "Dai Kundi"),
("AF-DAS", "AF-DAS", "Dasht-e Archi"),
("AF-DOA", "AF-DOA", "Dowlat Yar"),
("AF-FAR", "AF-FAR", "Farah"),
("AF-GAR", "AF-GAR", "Gardez"),
("AF-GHA", "AF-GHA", "Ghazni"),
("AF-GHA", "AF-GHA", "Ghazni City"),
("AF-GUL", "AF-GUL", "Gulistan"),
("AF-HOS", "AF-HOS", "Hoshi"),
("AF-IZA", "AF-IZA", "Izat Khel"),
("AF-JAL", "AF-JAL", "Jalalabad"),
("AF-KAF", "AF-KAF", "Kafir Qala"),
("AF-KAJ", "AF-KAJ", "Kajran"),
("AF-KAL", "AF-KAL", "Kalat"),
("AF-KAN", "AF-KAN", "Kandahar City"),
("AF-KAP", "AF-KAP", "Kapisa"),
("AF-KAR", "AF-KAR", "Karokh"),
("AF-KAS", "AF-KAS", "Kashan"),
("AF-KHA", "AF-KHA", "Khash"),
("AF-KHO", "AF-KHO", "Khost"),
("AF-KHW", "AF-KHW", "Khawhan"),
("AF-KON", "AF-KON", "Kondoz"),
("AF-KOT", "AF-KOT", "Kot"),
("AF-KOW", "AF-KOW", "Kowt-e Ashrow"),
("AF-KRY", "AF-KRY", "Khost City"),
("AF-KUH", "AF-KUH", "Kuhdasht"),
("AF-KUN", "AF-KUN", "Kunar"),
("AF-KUR", "AF-KUR", "Kurram"),
("AF-LAK", "AF-LAK", "Lashkar Gah"),
("AF-LAR", "AF-LAR", "Lar"),
("AF-LAT", "AF-LAT", "Latifiyah"),
("AF-LWG", "AF-LWG", "Lwara"),
("AF-MAD", "AF-MAD", "Mada Khel"),
("AF-MAI", "AF-MAI", "Maimana"),
("AF-MAL", "AF-MAL", "Malistan"),
("AF-MAN", "AF-MAN", "Mandozai"),
("AF-MAR", "AF-MAR", "Mardian"),
("AF-MAY", "AF-MAY", "Maymana"),
("AF-MES", "AF-MES", "Mes-e Aynak"),
("AF-MIY", "AF-MIY", "Mihtarlam"),
("AF-NAG", "AF-NAG", "Naghlu"),
("AF-NAN", "AF-NAN", "Nangarhar"),
("AF-NAW", "AF-NAW", "Nawa"),
("AF-NEJ", "AF-NEJ", "Nejrab"),
("AF-NET", "AF-NET", "Nerkh"),
("AF-NUZ", "AF-NUZ", "Nuristan"),
("AF-OMA", "AF-OMA", "Omna"),
("AF-ORU", "AF-ORU", "Oruzgan"),
("AF-OWR", "AF-OWR", "Owrzazan"),
("AF-PAG", "AF-PAG", "Paghman"),
("AF-PAK", "AF-PAK", "Paktia"),
("AF-PAR", "AF-PAR", "Parwan"),
("AF-PAT", "AF-PAT", "Patiya"),
("AF-PIA", "AF-PIA", "Pul-i-Alam"),
("AF-PKA", "AF-PKA", "Paktika"),
("AF-PKI", "AF-PKI", "Paktya"),
("AF-PUL", "AF-PUL", "Puli Alam"),
("AF-QAD", "AF-QAD", "Qadis"),
("AF-QAL", "AF-QAL", "Qalat"),
("AF-QAR", "AF-QAR", "Qarah Bagh"),
("AF-QIS", "AF-QIS", "Qishn"),
("AF-QZB", "AF-QZB", "Qizil Ribat"),
("AF-RUD", "AF-RUD", "Rud-e-Saraj"),
("AF-SAD", "AF-SAD", "Sada"),
("AF-SAM", "AF-SAM", "Samar Khel"),
("AF-SAN", "AF-SAN", "Sangin"),
("AF-SAR", "AF-SAR", "Sarobi"),
("AF-SEK", "AF-SEK", "Sekh"),
("AF-SEP", "AF-SEP", "Seppa"),
("AF-SER", "AF-SER", "Sere Kani"),
("AF-SHA", "AF-SHA", "Sharana"),
("AF-SHE", "AF-SHE", "Shengay"),
("AF-SHI", "AF-SHI", "Shindand"),
("AF-SHI", "AF-SHI", "Shir Khan"),
("AF-SHM", "AF-SHM", "Shahrak"),
("AF-SHT", "AF-SHT", "Shahr-e Tazeh"),
("AF-SHU", "AF-SHU", "Shunet"),
("AF-SID", "AF-SID", "Sidu Kurgan"),
("AF-SIR", "AF-SIR", "Sirkanay"),
("AF-SPI", "AF-SPI", "Spin Buldak"),
("AF-SRI", "AF-SRI", "Surubi"),
("AF-TAK", "AF-TAK", "Takhar"),
("AF-TAL", "AF-TAL", "Taloqan"),
("AF-TAR", "AF-TAR", "Tarangah"),
("AF-TIR", "AF-TIR", "Tirin Kot"),
("AF-UDA", "AF-UDA", "Uruzgan"),
("AF-WAG", "AF-WAG", "Waghaz"),
("AF-WAR", "AF-WAR", "Wardak"),
("AF-WKH", "AF-WKH", "Wakhim"),
("AF-WNH", "AF-WNH", "Wana"),
("AF-WRS", "AF-WRS", "Warsak"),
("AF-WTS", "AF-WTS", "Wats"),
("AF-WUS", "AF-WUS", "Wuswari"),
("AF-ZAB", "AF-ZAB", "Zabul"),
("AF-ZAD", "AF-ZAD", "Zadran"),
("AF-ZAR", "AF-ZAR", "Zaranj"),
("AF-ZHA", "AF-ZHA", "Zharay"),
("AF-ZUR", "AF-ZUR", "Zurmat");



-- albania


INSERT INTO countries VALUES 
("AL", "EU", "Albania", "Tirana");


INSERT INTO states VALUES
("AL-01", "AL", "Berat"),
("AL-02", "AL", "Dibër"),
("AL-03", "AL", "Durrës"),
("AL-04", "AL", "Elbasan"),
("AL-05", "AL", "Fier"),
("AL-06", "AL", "Gjirokastër"),
("AL-07", "AL", "Korçë"),
("AL-08", "AL", "Kukës"),
("AL-09", "AL", "Lezhë"),
("AL-10", "AL", "Shkodër"),
("AL-11", "AL", "Tiranë"),
("AL-12", "AL", "Vlorë");


INSERT INTO cities VALUES
("AL-TIA", "AL-11", "Tirana"),
("AL-DIB", "AL-09", "Peshkopi"),
("AL-DUR", "AL-03", "Durrës"),
("AL-VLO", "AL-12", "Vlorë"),
("AL-SHK", "AL-10", "Shkodër"),
("AL-BR", "AL-01", "Berat"),
("AL-EL", "AL-04", "Elbasan"),
("AL-GJ", "AL-06", "Gjirokastër"),
("AL-KR", "AL-07", "Korçë"),
("AL-LB", "AL-09", "Lezhë"),
("AL-PG", "AL-05", "Pogradec"),
("AL-PR", "AL-04", "Përmet"),
("AL-KU", "AL-07", "Kukës"),
("AL-VR", "AL-11", "Vorë"),
("AL-LU", "AL-08", "Lushnjë"),
("AL-FR", "AL-02", "Fushë-Arrëz"),
("AL-KL", "AL-05", "Këlcyra"),
("AL-PP", "AL-06", "Përrenjas"),
("AL-TE", "AL-04", "Tepelenë"),
("AL-MR", "AL-10", "Mamurras"),
("AL-LZ", "AL-08", "Laç"),
("AL-KB", "AL-08", "Kurbin"),
("AL-BU", "AL-02", "Bulqizë"),
("AL-DR", "AL-09", "Dibër"),
("AL-PE", "AL-05", "Peqin"),
("AL-MT", "AL-12", "Milot"),
("AL-MS", "AL-04", "Mallakastër"),
("AL-KR", "AL-01", "Kuçovë"),
("AL-KC", "AL-04", "Krrabë"),
("AL-PU", "AL-06", "Përmet"),
("AL-TE", "AL-03", "Tërnavë"),
("AL-TL", "AL-10", "Tropojë"),
("AL-DT", "AL-03", "Dajt"),
("AL-SH", "AL-06", "Sarandë"),
("AL-PR", "AL-06", "Përmet"),
("AL-FS", "AL-12", "Fier-Shegan"),
("AL-BR", "AL-07", "Bulqizë"),
("AL-MK", "AL-12", "Mavrovë"),
("AL-SN", "AL-03", "Shijak"),
("AL-DT", "AL-11", "Dajt"),
("AL-KC", "AL-11", "Krrabë");

-- algeria

INSERT INTO countries VALUES 
("DZ", "AF", "Algeria", "Algiers");

INSERT INTO states VALUES
("DZ-01", "DZ", "Adrar"),
("DZ-02", "DZ", "Chlef"),
("DZ-03", "DZ", "Laghouat"),
("DZ-04", "DZ", "Oum El Bouaghi"),
("DZ-05", "DZ", "Batna"),
("DZ-06", "DZ", "Béjaïa"),
("DZ-07", "DZ", "Biskra"),
("DZ-08", "DZ", "Béchar"),
("DZ-09", "DZ", "Blida"),
("DZ-10", "DZ", "Bouira"),
("DZ-11", "DZ", "Tamanrasset"),
("DZ-12", "DZ", "Tébessa"),
("DZ-13", "DZ", "Tlemcen"),
("DZ-14", "DZ", "Tiaret"),
("DZ-15", "DZ", "Tizi Ouzou"),
("DZ-16", "DZ", "Algiers"),
("DZ-17", "DZ", "Djelfa"),
("DZ-18", "DZ", "Jijel"),
("DZ-19", "DZ", "Sétif"),
("DZ-20", "DZ", "Saïda");

INSERT INTO cities VALUES
("DZ-16-ALG", "DZ-16", "Algiers"),
("DZ-01-ADR", "DZ-01", "Adrar"),
("DZ-05-BAT", "DZ-05", "Batna"),
("DZ-09-BLD", "DZ-09", "Blida"),
("DZ-08-BEC", "DZ-08", "Béchar"),
("DZ-06-BJA", "DZ-06", "Béjaïa"),
("DZ-07-BSK", "DZ-07", "Biskra"),
("DZ-10-BUI", "DZ-10", "Bouira"),
("DZ-02-CLF", "DZ-02", "Chlef"),
("DZ-18-DJL", "DZ-18", "Djelfa"),
("DZ-12-TEB", "DZ-12", "Tébessa"),
("DZ-11-TAM", "DZ-11", "Tamanrasset"),
("DZ-15-TIZ", "DZ-15", "Tizi Ouzou"),
("DZ-19-SET", "DZ-19", "Sétif"),
("DZ-03-LAG", "DZ-03", "Laghouat"),
("DZ-17-DJF", "DZ-17", "Djelfa"),
("DZ-14-TIA", "DZ-14", "Tiaret"),
("DZ-20-SAI", "DZ-20", "Saïda");

-- andorra

INSERT INTO countries VALUES 
("AD", "EU", "Andorra", "Andorra la Vella");

INSERT INTO states VALUES
("AD-02", "AD", "Canillo"),
("AD-03", "AD", "Encamp"),
("AD-04", "AD", "La Massana"),
("AD-05", "AD", "Ordino"),
("AD-06", "AD", "Sant Julia de Loria"),
("AD-07", "AD", "Andorra la Vella"),
("AD-08", "AD", "Escaldes-Engordany");

INSERT INTO cities VALUES
("AD-07-AND", "AD-07", "Andorra la Vella"),
("AD-08-ESC", "AD-08", "Escaldes-Engordany"),
("AD-02-CAN", "AD-02", "Canillo"),
("AD-03-ENC", "AD-03", "Encamp"),
("AD-04-LAM", "AD-04", "La Massana"),
("AD-05-ORD", "AD-05", "Ordino"),
("AD-06-SJL", "AD-06", "Sant Julia de Loria"),
("AD-02-SOL", "AD-02", "Soldeu"),
("AD-03-PAS", "AD-03", "Pas de la Casa"),
("AD-04-AIX", "AD-04", "Aixovall"),
("AD-05-LES", "AD-05", "Les Bons"),
("AD-06-ESC", "AD-06", "Escales");

-- angola

INSERT INTO countries VALUES 
("AO", "AF", "Angola", "Luanda");

INSERT INTO states VALUES
("AO-BGO", "AO", "Bengo"),
("AO-BGU", "AO", "Benguela"),
("AO-BIE", "AO", "Bie"),
("AO-CAB", "AO", "Cabinda"),
("AO-CCU", "AO", "Cuando Cubango"),
("AO-CNO", "AO", "Cuanza Norte"),
("AO-CUS", "AO", "Cuanza Sul"),
("AO-CNN", "AO", "Cunene"),
("AO-HUA", "AO", "Huambo"),
("AO-HUI", "AO", "Huila"),
("AO-LUA", "AO", "Luanda"),
("AO-LNO", "AO", "Lunda Norte"),
("AO-LSU", "AO", "Lunda Sul"),
("AO-MAL", "AO", "Malanje"),
("AO-MOX", "AO", "Moxico"),
("AO-NAM", "AO", "Namibe"),
("AO-UIG", "AO", "Uige"),
("AO-ZAI", "AO", "Zaire");

INSERT INTO cities VALUES
("AO-LUA-LAD", "AO-LUA", "Luanda"),
("AO-BGU-CAB", "AO-BGU", "Benguela"),
("AO-BIE-CUB", "AO-BIE", "Cubal"),
("AO-CNO-NOV", "AO-CNO", "N'dalatando"),
("AO-CCU-MEN", "AO-CCU", "Menongue"),
("AO-CUS-SAU", "AO-CUS", "Sumbe"),
("AO-CNN-OHN", "AO-CNN", "Ondjiva"),
("AO-HUA-HUA", "AO-HUA", "Huambo"),
("AO-HUI-LUB", "AO-HUI", "Lubango"),
("AO-LUA-VIAN", "AO-LUA", "Viana"),
("AO-LNO-DUN", "AO-LNO", "Dundo"),
("AO-LSU-SAU", "AO-LSU", "Saurimo"),
("AO-MAL-MAL", "AO-MAL", "Malanje"),
("AO-MOX-LUE", "AO-MOX", "Luena"),
("AO-NAM-MOB", "AO-NAM", "Moçâmedes"),
("AO-UIG-UIG", "AO-UIG", "Uíge"),
("AO-ZAI-MBA", "AO-ZAI", "M'banza Kongo"),
("AO-LUA-LOB", "AO-LUA", "Lobito"),
("AO-BGU-LUA", "AO-BGU", "Lobito"),
("AO-BGU-CAT", "AO-BGU", "Catumbela"),
("AO-BIE-LUB", "AO-BIE", "Lubango"),
("AO-CNO-AND", "AO-CNO", "Andulo"),
("AO-CNO-NAM", "AO-CNO", "Nambuangongo"),
("AO-CCU-CUT", "AO-CCU", "Cuito Cuanavale"),
("AO-CUS-AMI", "AO-CUS", "Amboim"),
("AO-CNN-KUA", "AO-CNN", "Kuamato"),
("AO-CNN-OCA", "AO-CNN", "Ocau"),
("AO-HUA-KUL", "AO-HUA", "Kuito"),
("AO-HUI-QUI", "AO-HUI", "Quilengues"),
("AO-LNO-CAC", "AO-LNO", "Cacolo"),
("AO-LNO-CAP", "AO-LNO", "Capenda Camulemba"),
("AO-LSU-MUI", "AO-LSU", "Muconda"),
("AO-LSU-DAL", "AO-LSU", "Dala"),
("AO-MAL-CAN", "AO-MAL", "Cangandala"),
("AO-MAL-LUE", "AO-MAL", "Luau"),
("AO-MOX-CAM", "AO-MOX", "Camanongue"),
("AO-NAM-TOM", "AO-NAM", "Tômbua"),
("AO-NAM-NAM", "AO-NAM", "Namibe"),
("AO-UIG-MAE", "AO-UIG", "Maconge"),
("AO-UIG-NEB", "AO-UIG", "Negage"),
("AO-ZAI-NZC", "AO-ZAI", "N'zeto"),
("AO-ZAI-SOY", "AO-ZAI", "Soyo");

-- argentina

INSERT INTO countries VALUES 
("AR", "SA", "Argentina", "Buenos Aires");


INSERT INTO states VALUES
("AR-B", "AR", "Buenos Aires"),
("AR-C", "AR", "Catamarca"),
("AR-CHA", "AR", "Chaco"),
("AR-U", "AR", "Chubut"),
("AR-CO", "AR", "Córdoba"),
("AR-CR", "AR", "Corrientes"),
("AR-ER", "AR", "Entre Ríos"),
("AR-F", "AR", "Formosa"),
("AR-J", "AR", "Jujuy"),
("AR-L", "AR", "La Pampa"),
("AR-G", "AR", "La Rioja"),
("AR-M", "AR", "Mendoza"),
("AR-N", "AR", "Misiones"),
("AR-Q", "AR", "Neuquén"),
("AR-R", "AR", "Río Negro"),
("AR-A", "AR", "Salta"),
("AR-JU", "AR", "San Juan"),
("AR-S", "AR", "San Luis"),
("AR-SG", "AR", "Santa Cruz"),
("AR-SA", "AR", "Santa Fe"),
("AR-SE", "AR", "Santiago del Estero"),
("AR-T", "AR", "Tierra del Fuego"),
("AR-X", "AR", "Tucumán");

INSERT INTO cities VALUES
("AR-B-BSAS", "AR-B", "Buenos Aires"),
("AR-C-CAT", "AR-C", "San Fernando del Valle de Catamarca"),
("AR-CHA-RES", "AR-CHA", "Resistencia"),
("AR-U-COM", "AR-U", "Comodoro Rivadavia"),
("AR-CO-CBA", "AR-CO", "Córdoba"),
("AR-CR-COR", "AR-CR", "Corrientes"),
("AR-ER-PNA", "AR-ER", "Paraná"),
("AR-F-FOR", "AR-F", "Formosa"),
("AR-J-SJ", "AR-J", "San Salvador de Jujuy"),
("AR-L-SLP", "AR-L", "Santa Rosa"),
("AR-G-LR", "AR-G", "La Rioja"),
("AR-M-MZA", "AR-M", "Mendoza"),
("AR-N-POS", "AR-N", "Posadas"),
("AR-Q-NQN", "AR-Q", "Neuquén"),
("AR-R-VDC", "AR-R", "Viedma"),
("AR-A-SAL", "AR-A", "Salta"),
("AR-JU-SJU", "AR-JU", "San Juan"),
("AR-SU-RAF", "AR-S", "San Luis"),
("AR-SG-RGL", "AR-SG", "Río Gallegos"),
("AR-SA-ROS", "AR-SA", "Rosario"),
("AR-SE-SDE", "AR-SE", "Santiago del Estero"),
("AR-T-RGA", "AR-T", "Ushuaia"),
("AR-X-TUC", "AR-X", "San Miguel de Tucumán"),
("AR-B-QUIL", "AR-B", "Quilmes"),
("AR-B-MOR", "AR-B", "Morón"),
("AR-C-RC", "AR-C", "Río Cuarto"),
("AR-C-ALC", "AR-C", "Alta Gracia"),
("AR-CHA-SAR", "AR-CHA", "Sáenz Peña"),
("AR-CHA-ROC", "AR-CHA", "Roque Sáenz Peña"),
("AR-U-TRE", "AR-U", "Trelew"),
("AR-U-RAD", "AR-U", "Rawson"),
("AR-CO-RCF", "AR-CO", "Río Cuarto"),
("AR-CR-GUA", "AR-CR", "Goya"),
("AR-ER-GUA", "AR-ER", "Gualeguaychú"),
("AR-F-RES", "AR-F", "Formosa"),
("AR-J-LIR", "AR-J", "Libertador General San Martín"),
("AR-L-STL", "AR-L", "Santa Rosa de Toay"),
("AR-G-CAP", "AR-G", "Capital"),
("AR-M-MAL", "AR-M", "Malargüe"),
("AR-N-AP", "AR-N", "Apóstoles"),
("AR-Q-ZAP", "AR-Q", "Zapala"),
("AR-R-CHO", "AR-R", "Choele Choel"),
("AR-A-TAR", "AR-A", "Tartagal"),
("AR-JU-LDR", "AR-JU", "Libertador General San Martín"),
("AR-SU-VMA", "AR-S", "Villa Mercedes"),
("AR-SG-RGL", "AR-SG", "Río Gallegos"),
("AR-SA-VC", "AR-SA", "Villa Constitución"),
("AR-SE-LAP", "AR-SE", "La Banda"),
("AR-T-RTA", "AR-T", "Río Grande"),
("AR-X-YER", "AR-X", "Yerba Buena");

-- Armenia

INSERT INTO countries VALUES 
("AM", "AS", "Armenia", "Yerevan");

INSERT INTO states VALUES
("AM-AG", "AM", "Aragatsotn"),
("AM-AR", "AM", "Ararat"),
("AM-AV", "AM", "Armavir"),
("AM-ER", "AM", "Erevan"),
("AM-GR", "AM", "Geghark'unik'"),
("AM-KT", "AM", "Kotayk'"),
("AM-LO", "AM", "Lorri"),
("AM-SH", "AM", "Shirak"),
("AM-SU", "AM", "Syunik'"),
("AM-TV", "AM", "Tavush"),
("AM-VD", "AM", "Vayots' Dzor");

INSERT INTO cities VALUES
("AM-ER-YRVN", "AM-ER", "Yerevan"),
("AM-AG-ASD", "AM-AG", "Ashtarak"),
("AM-AR-AVSH", "AM-AR", "Ararat"),
("AM-AV-ARM", "AM-AV", "Armavir"),
("AM-GR-GYO", "AM-GR", "Gyumri"),
("AM-KT-HRA", "AM-KT", "Hrazdan"),
("AM-LO-VAN", "AM-LO", "Vanadzor"),
("AM-SH-GUM", "AM-SH", "Gyumri"),
("AM-SU-KAP", "AM-SU", "Kapan"),
("AM-TV-IJE", "AM-TV", "Ijevan"),
("AM-VD-JER", "AM-VD", "Jermuk"),
("AM-ER-ASL", "AM-ER", "Ashtarak"),
("AM-ER-TAL", "AM-ER", "Talin"),
("AM-ER-ARZ", "AM-ER", "Arzni"),
("AM-AR-ARAR", "AM-AR", "Ararat"),
("AM-AR-MAS", "AM-AR", "Masis"),
("AM-AR-VED", "AM-AR", "Vedi"),
("AM-AV-ARM", "AM-AV", "Armavir"),
("AM-AV-MAS", "AM-AV", "Masis"),
("AM-GR-GYO", "AM-GR", "Gyumri"),
("AM-GR-TAL", "AM-GR", "Talin"),
("AM-KT-HRA", "AM-KT", "Hrazdan"),
("AM-KT-ALP", "AM-KT", "Abovyan"),
("AM-LO-VAN", "AM-LO", "Vanadzor"),
("AM-LO-ALM", "AM-LO", "Alaverdi"),
("AM-SH-GUM", "AM-SH", "Gyumri"),
("AM-SH-TAL", "AM-SH", "Talin"),
("AM-SU-KAP", "AM-SU", "Kapan"),
("AM-SU-MEG", "AM-SU", "Meghri"),
("AM-TV-IJE", "AM-TV", "Ijevan"),
("AM-TV-DIL", "AM-TV", "Dilijan"),
("AM-VD-JER", "AM-VD", "Jermuk"),
("AM-VD-VAY", "AM-VD", "Vayk");

-- Aruba

INSERT INTO countries VALUES 
("AW", "NA", "Aruba", "Oranjestad");

INSERT INTO cities VALUES
("AW-ORJ", "AW", "Oranjestad"),
("AW-NOO", "AW", "Noord"),
("AW-SAN", "AW", "San Nicolas"),
("AW-SAV", "AW", "Savaneta"),
("AW-PAR", "AW", "Paradera"),
("AW-ROO", "AW", "Rooi"),
("AW-SAN", "AW", "Santa Cruz"),
("AW-SLA", "AW", "Sint Nicolaas"),
("AW-SMC", "AW", "Sint Michiel"),
("AW-SOC", "AW", "Seroe Colorado"),
("AW-SOL", "AW", "Solito"),
("AW-WAN", "AW", "Wandelaar"),
("AW-WAY", "AW", "Wayaca"),
("AW-WIL", "AW", "Willem III"),
("AW-ZON", "AW", "Zonderschoon");

-- Australia

INSERT INTO countries VALUES 
("AU", "OC", "Australia", "Canberra");

INSERT INTO states VALUES
("AU-NSW", "AU", "New South Wales"),
("AU-VIC", "AU", "Victoria"),
("AU-QLD", "AU", "Queensland"),
("AU-WA", "AU", "Western Australia"),
("AU-SA", "AU", "South Australia"),
("AU-TAS", "AU", "Tasmania"),
("AU-ACT", "AU", "Australian Capital Territory"),
("AU-NT", "AU", "Northern Territory");

INSERT INTO cities VALUES
("AU-NSW-ALB", "AU-NSW", "Albury"),
("AU-NSW-WOD", "AU-NSW", "Wodonga"),
("AU-NSW-ORA", "AU-NSW", "Orange"),
("AU-NSW-TAM", "AU-NSW", "Tamworth"),
("AU-NSW-GRA", "AU-NSW", "Grafton"),
("AU-NSW-ARM", "AU-NSW", "Armidale"),
("AU-NSW-DUB", "AU-NSW", "Dubbo"),
("AU-NSW-BAT", "AU-NSW", "Bathurst"),
("AU-VIC-GEEL", "AU-VIC", "Geelong"),
("AU-VIC-BALL", "AU-VIC", "Ballarat"),
("AU-VIC-BEND", "AU-VIC", "Bendigo"),
("AU-VIC-MORN", "AU-VIC", "Mornington"),
("AU-VIC-GEEL", "AU-VIC", "Geelong"),
("AU-VIC-GEEL", "AU-VIC", "Geelong West"),
("AU-VIC-SHEP", "AU-VIC", "Shepparton"),
("AU-VIC-MILD", "AU-VIC", "Mildura"),
("AU-VIC-WARR", "AU-VIC", "Warrnambool"),
("AU-VIC-WANG", "AU-VIC", "Wangaratta"),
("AU-QLD-GLA", "AU-QLD", "Gladstone"),
("AU-QLD-BUN", "AU-QLD", "Bundaberg"),
("AU-QLD-HER", "AU-QLD", "Hervey Bay"),
("AU-QLD-ROC", "AU-QLD", "Rockhampton"),
("AU-QLD-TOW", "AU-QLD", "Townsville"),
("AU-QLD-MKY", "AU-QLD", "Mackay"),
("AU-QLD-TOO", "AU-QLD", "Toowoomba"),
("AU-QLD-SUN", "AU-QLD", "Sunshine Coast"),
("AU-WA-BRO", "AU-WA", "Broome"),
("AU-WA-KAL", "AU-WA", "Kalgoorlie-Boulder"),
("AU-WA-KAR", "AU-WA", "Karratha"),
("AU-WA-GER", "AU-WA", "Geraldton"),
("AU-WA-ALB", "AU-WA", "Albany"),
("AU-WA-BUN", "AU-WA", "Bunbury"),
("AU-SA-MOU", "AU-SA", "Mount Gambier"),
("AU-SA-PTA", "AU-SA", "Port Augusta"),
("AU-SA-MUR", "AU-SA", "Murray Bridge"),
("AU-SA-REN", "AU-SA", "Renmark"),
("AU-SA-why", "AU-SA", "Whyalla"),
("AU-TAS-LON", "AU-TAS", "Launceston"),
("AU-TAS-BUR", "AU-TAS", "Burnie"),
("AU-TAS-DEV", "AU-TAS", "Devonport"),
("AU-TAS-STH", "AU-TAS", "South Hobart"),
("AU-ACT-CBR", "AU-ACT", "Canberra"),
("AU-NT-DAR", "AU-NT", "Darwin"),
("AU-NT-PAL", "AU-NT", "Palmerston");


-- Austria

INSERT INTO countries VALUES 
("AT", "EU", "Austria", "Vienna");

INSERT INTO states VALUES
("AT-1", "AT", "Burgenland"),
("AT-2", "AT", "Carinthia"),
("AT-3", "AT", "Lower Austria"),
("AT-4", "AT", "Upper Austria"),
("AT-5", "AT", "Salzburg"),
("AT-6", "AT", "Styria"),
("AT-7", "AT", "Tyrol"),
("AT-8", "AT", "Vorarlberg"),
("AT-9", "AT", "Vienna");

INSERT INTO cities VALUES
("AT-1-EIS-RA", "AT-1-EIS", "Raiding"),
("AT-1-EIS-OB", "AT-1-EIS", "Oberpullendorf"),
("AT-1-EIS-KO", "AT-1-EIS", "Kobersdorf"),
("AT-2-KLU-KLA", "AT-2-KLU", "Klagenfurt am Wörthersee"),
("AT-2-KLU-VIK", "AT-2-KLU", "Viktring"),
("AT-2-KLU-WOE", "AT-2-KLU", "Wölfnitz"),
("AT-3-STP-STP", "AT-3-STP", "St. Pölten"),
("AT-3-STP-KLO", "AT-3-STP", "Klosterneuburg"),
("AT-3-STP-BAD", "AT-3-STP", "Baden"),
("AT-4-LNZ-LNZ", "AT-4-LNZ", "Linz"),
("AT-4-LNZ-LEO", "AT-4-LNZ", "Leonding"),
("AT-4-LNZ-TRA", "AT-4-LNZ", "Traun"),
("AT-5-SZG-SZG", "AT-5-SZG", "Salzburg"),
("AT-5-SZG-HAL", "AT-5-SZG", "Hallein"),
("AT-5-SZG-SA", "AT-5-SZG", "Saalfelden am Steinernen Meer"),
("AT-6-GRA-GRA", "AT-6-GRA", "Graz"),
("AT-6-GRA-LEI", "AT-6-GRA", "Leibnitz"),
("AT-6-GRA-DEU", "AT-6-GRA", "Deutschlandsberg"),
("AT-7-INN-INN", "AT-7-INN", "Innsbruck"),
("AT-7-INN-HAL", "AT-7-INN", "Hall in Tirol"),
("AT-7-INN-SEF", "AT-7-INN", "Seefeld in Tirol"),
("AT-8-BRE-BRE", "AT-8-BRE", "Bregenz"),
("AT-8-BRE-DOR", "AT-8-BRE", "Dornbirn"),
("AT-8-BRE-FEL", "AT-8-BRE", "Feldkirch"),
("AT-9-VIE-VIE", "AT-9-VIE", "Vienna"),
("AT-9-VIE-KLO", "AT-9-VIE", "Klosterneuburg"),
("AT-9-VIE-SCH", "AT-9-VIE", "Schwechat");

-- Azerbaijan

INSERT INTO countries VALUES 
("AZ", "AS", "Azerbaijan", "Baku");

INSERT INTO states VALUES
("AZ-BA", "AZ", "Baki"),
("AZ-GA", "AZ", "Ganja"),
("AZ-LA", "AZ", "Lankaran"),
("AZ-MI", "AZ", "Mingachevir"),
("AZ-NA", "AZ", "Naftalan"),
("AZ-SA", "AZ", "Shaki"),
("AZ-SM", "AZ", "Sumgait");

INSERT INTO cities VALUES
("AZ-BA-BAK-SAB", "AZ-BA-BAK", "Sabail"),
("AZ-BA-BAK-SUR", "AZ-BA-BAK", "Surakhani"),
("AZ-BA-BAK-NIZ", "AZ-BA-BAK", "Nizami"),
("AZ-BA-BAK-SMI", "AZ-BA-BAK", "Sabunchi"),
("AZ-BA-BAK-KHI", "AZ-BA-BAK", "Khirdalan"),
("AZ-GA-GAN-GAD", "AZ-GA-GAN", "Gadabay"),
("AZ-GA-GAN-GOR", "AZ-GA-GAN", "Goranboy"),
("AZ-GA-GAN-GOY", "AZ-GA-GAN", "Goygol"),
("AZ-GA-GAN-SAM", "AZ-GA-GAN", "Samukh"),
("AZ-LA-LAN-AST", "AZ-LA-LAN", "Astara"),
("AZ-LA-LAN-LAN", "AZ-LA-LAN", "Lankaran"),
("AZ-LA-LAN-LER", "AZ-LA-LAN", "Lerik"),
("AZ-LA-LAN-MAS", "AZ-LA-LAN", "Masalli"),
("AZ-MI-MIN-MIN", "AZ-MI-MIN", "Mingachevir"),
("AZ-NA-NAF-NAF", "AZ-NA-NAF", "Naftalan"),
("AZ-SA-SAK-SAK", "AZ-SA-SAK", "Shaki"),
("AZ-SA-SAK-OGU", "AZ-SA-SAK", "Oghuz");

-- antigua and Barbuda

INSERT INTO countries VALUES 
("AG", "NA", "Antigua and Barbuda", "St. John's");

INSERT INTO cities VALUES
("AG-01", "AG", "St. John's"),
("AG-02", "AG", "All Saints"),
("AG-03", "AG", "Liberta"),
("AG-04", "AG", "Bolands"),
("AG-05", "AG", "Potters Village"),
("AG-06", "AG", "Codrington"),
("AG-07", "AG", "Parham"),
("AG-08", "AG", "Carlisle"),
("AG-09", "AG", "Swetes"),
("AG-10", "AG", "Falmouth"),
("AG-11", "AG", "Cedar Grove"),
("AG-12", "AG", "Potworks Reservoir"),
("AG-13", "AG", "Freemans Village"),
("AG-14", "AG", "Pigotts"),
("AG-15", "AG", "Codrington Village"),
("AG-16", "AG", "English Harbour Town"),
("AG-17", "AG", "Buckleys"),
("AG-18", "AG", "Old Road"),
("AG-19", "AG", "Five Islands Village"),
("AG-20", "AG", "Bendals"),
("AG-21", "AG", "Willikies"),
("AG-22", "AG", "Sweets"),
("AG-23", "AG", "Freetown");

-- Bahamas

INSERT INTO countries VALUES 
("BS", "NA", "Bahamas", "Nassau");

INSERT INTO states VALUES
("BS-NE", "BS", "New Providence"),
("BS-GR", "BS", "Grand Bahama"),
("BS-AB", "BS", "Abaco"),
("BS-EX", "BS", "Exuma"),
("BS-BI", "BS", "Bimini"),
("BS-AN", "BS", "Andros"),
("BS-EL", "BS", "Eleuthera"),
("BS-CA", "BS", "Cat Island"),
("BS-LT", "BS", "Long Island");

INSERT INTO cities VALUES
("BS-NE-NAS-AP", "BS-NE-NAS", "Arawak Cay"),
("BS-NE-NAS-CI", "BS-NE-NAS", "Cable Beach"),
("BS-NE-NAS-EH", "BS-NE-NAS", "East Hill Street"),
("BS-NE-NAS-GB", "BS-NE-NAS", "Gambier"),
("BS-NE-NAS-MP", "BS-NE-NAS", "Montagu"),
("BS-NE-NAS-OP", "BS-NE-NAS", "Oakes Field"),
("BS-NE-NAS-PG", "BS-NE-NAS", "Paradise Island"),
("BS-GR-FPO-LC", "BS-GR-FPO", "Lucaya"),
("BS-GR-FPO-PL", "BS-GR-FPO", "Pinders Point"),
("BS-GR-FPO-TR", "BS-GR-FPO", "West End"),
("BS-AB-MHH-MH", "BS-AB-MHH", "Marsh Harbour"),
("BS-AB-MHH-MT", "BS-AB-MHH", "Murphy Town"),
("BS-EX-GGT-FC", "BS-EX-GGT", "Farmer's Cay"),
("BS-EX-GGT-RS", "BS-EX-GGT", "Rokers Point Settlement"),
("BS-BI-BS-BA", "BS-BI-BS", "Bailey Town"),
("BS-BI-BS-PA", "BS-BI-BS", "Porgy Bay"),
("BS-AN-ASD-CT", "BS-AN-ASD", "Central Andros"),
("BS-AN-ASD-MS", "BS-AN-ASD", "Mastic Point"),
("BS-EL-GHB-GH", "BS-EL-GHB", "Governor's Harbour"),
("BS-EL-GHB-JI", "BS-EL-GHB", "James Cistern"),
("BS-CA-ATC-AT", "BS-CA-ATC", "Arthur's Town"),
("BS-CA-ATC-HP", "BS-CA-ATC", "High Rock"),
("BS-LT-CLA-CL", "BS-LT-CLA", "Clarence Town"),
("BS-LT-CLA-GH", "BS-LT-CLA", "Gray's"),
("BS-LT-CLA-MA", "BS-LT-CLA", "Mangrove Cay");

-- Bahrain

INSERT INTO countries VALUES 
("BH", "AS", "Bahrain", "Manama");

INSERT INTO cities VALUES
("BH-13", "BH", "Manama"),
("BH-16", "BH", "Muharraq"),
("BH-14", "BH", "Riffa"),
("BH-15", "BH", "Hamad Town"),
("BH-17", "BH", "A'ali"),
("BH-18", "BH", "Isa Town"),
("BH-19", "BH", "Sitra"),
("BH-20", "BH", "Jidhafs"),
("BH-21", "BH", "Al-Malikiyah"),
("BH-22", "BH", "Zinj"),
("BH-23", "BH", "Adliya"),
("BH-24", "BH", "Juffair"),
("BH-25", "BH", "Saar"),
("BH-26", "BH", "Budaiya"),
("BH-27", "BH", "Hidd"),
("BH-28", "BH", "Galali"),
("BH-29", "BH", "Tubli"),
("BH-30", "BH", "Sanabis"),
("BH-31", "BH", "Malkiya"),
("BH-32", "BH", "Bani Jamra");

-- Bangladesh

INSERT INTO countries VALUES 
("BD", "AS", "Bangladesh", "Dhaka");

INSERT INTO states VALUES
("BD-DH", "BD", "Dhaka"),
("BD-CT", "BD", "Chittagong"),
("BD-KH", "BD", "Khulna"),
("BD-RA", "BD", "Rajshahi"),
("BD-BR", "BD", "Barisal"),
("BD-SY", "BD", "Sylhet"),
("BD-RA", "BD", "Rangpur"),
("BD-MY", "BD", "Mymensingh"),
("BD-BG", "BD", "Bagerhat"),
("BD-BH", "BD", "Bandarban"),
("BD-BP", "BD", "Barguna"),
("BD-BM", "BD", "Brahmanbaria"),
("BD-BN", "BD", "Bogra"),
("BD-BS", "BD", "Bogra Sadar"),
("BD-BE", "BD", "Bhola"),
("BD-CO", "BD", "Comilla"),
("BD-CO", "BD", "Chandpur"),
("BD-CP", "BD", "Chapai Nawabganj"),
("BD-CT", "BD", "Cox's Bazar"),
("BD-DM", "BD", "Dhaka"),
("BD-DI", "BD", "Dinajpur"),
("BD-FA", "BD", "Faridpur"),
("BD-FR", "BD", "Feni"),
("BD-GA", "BD", "Gaibandha"),
("BD-GZ", "BD", "Gazipur"),
("BD-GR", "BD", "Gopalganj"),
("BD-HB", "BD", "Habiganj"),
("BD-JA", "BD", "Jamalpur"),
("BD-JS", "BD", "Jashore"),
("BD-JL", "BD", "Jhalokathi"),
("BD-JO", "BD", "Jhenaidah"),
("BD-JO", "BD", "Joypurhat"),
("BD-KI", "BD", "Kishoreganj"),
("BD-KH", "BD", "Khagrachari"),
("BD-KU", "BD", "Kurigram"),
("BD-KU", "BD", "Kushtia"),
("BD-LK", "BD", "Lakshmipur"),
("BD-LA", "BD", "Lalmonirhat"),
("BD-MA", "BD", "Madaripur"),
("BD-MA", "BD", "Magura"),
("BD-MJ", "BD", "Meherpur"),
("BD-MO", "BD", "Moulvibazar"),
("BD-ML", "BD", "Munshiganj"),
("BD-MS", "BD", "Mymensingh"),
("BD-NA", "BD", "Naogaon"),
("BD-NR", "BD", "Narail"),
("BD-NR", "BD", "Narayanganj"),
("BD-NA", "BD", "Narsingdi"),
("BD-NB", "BD", "Natore"),
("BD-NO", "BD", "Netrokona"),
("BD-NU", "BD", "Nilphamari"),
("BD-OK", "BD", "Nokhali"),
("BD-PI", "BD", "Panchagarh"),
("BD-PA", "BD", "Patuakhali"),
("BD-PR", "BD", "Pabna"),
("BD-RA", "BD", "Rangamati"),
("BD-RA", "BD", "Rajbari"),
("BD-SA", "BD", "Satkhira"),
("BD-SI", "BD", "Sirajganj"),
("BD-SU", "BD", "Sunamganj"),
("BD-TA", "BD", "Tangail"),
("BD-TH", "BD", "Thakurgaon");


INSERT INTO cities VALUES
("BD-DH-01", "BD-DH", "Dhaka"),
("BD-DH-02", "BD-DH", "Narayanganj"),
("BD-DH-03", "BD-DH", "Gazipur"),
("BD-DH-04", "BD-DH", "Tangail"),
("BD-CT-05", "BD-CT", "Chittagong"),
("BD-CT-06", "BD-CT", "Comilla"),
("BD-CT-07", "BD-CT", "Feni"),
("BD-CT-08", "BD-CT", "Brahmanbaria"),
("BD-KH-09", "BD-KH", "Khulna"),
("BD-KH-10", "BD-KH", "Jessore"),
("BD-KH-11", "BD-KH", "Satkhira"),
("BD-RA-12", "BD-RA", "Rajshahi"),
("BD-RA-13", "BD-RA", "Bogra"),
("BD-RA-14", "BD-RA", "Pabna"),
("BD-BR-15", "BD-BR", "Barisal"),
("BD-BR-16", "BD-BR", "Patuakhali"),
("BD-BR-17", "BD-BR", "Bhola"),
("BD-SY-18", "BD-SY", "Sylhet"),
("BD-SY-19", "BD-SY", "Moulvibazar"),
("BD-SY-20", "BD-SY", "Habiganj"),
("BD-RA-21", "BD-RA", "Rangpur"),
("BD-RA-22", "BD-RA", "Dinajpur"),
("BD-RA-23", "BD-RA", "Thakurgaon"),
("BD-MY-24", "BD-MY", "Mymensingh"),
("BD-MY-25", "BD-MY", "Jamalpur"),
("BD-MY-26", "BD-MY", "Netrokona"),

-- Barbados

INSERT INTO countries VALUES 
("BB", "NA", "Barbados", "Bridgetown");

INSERT INTO cities VALUES
("BB-11", "BB", "Black Rock"),
("BB-12", "BB", "Greenland"),
("BB-13", "BB", "Hillaby"),
("BB-14", "BB", "Little Bay"),
("BB-15", "BB", "Mangrove"),
("BB-16", "BB", "River Bay"),
("BB-17", "BB", "Road View"),
("BB-18", "BB", "Rose Hill"),
("BB-19", "BB", "Six Cross Roads"),
("BB-20", "BB", "Six Mens"),
("BB-21", "BB", "Sunbury"),
("BB-22", "BB", "Walkers"),
("BB-23", "BB", "Welches"),
("BB-24", "BB", "Weston"),
("BB-25", "BB", "Worthing"),
("BB-26", "BB", "Atlantic Shores"),
("BB-27", "BB", "Benn Hill"),
("BB-28", "BB", "Bridgetown Garrison"),
("BB-29", "BB", "Cave Hill"),
("BB-30", "BB", "Clinketts"),
("BB-31", "BB", "Clifton Hall"),
("BB-32", "BB", "Culpepper Island"),
("BB-33", "BB", "Diamond Valley"),
("BB-34", "BB", "Durants"),
("BB-35", "BB", "Flat Rock"),
("BB-36", "BB", "Fortesque"),
("BB-37", "BB", "Friendly Hall"),
("BB-38", "BB", "Fustic"),
("BB-39", "BB", "Gibbes"),
("BB-40", "BB", "Greenidge"),
("BB-41", "BB", "Harmony Hall"),
("BB-42", "BB", "Hopewell"),
("BB-43", "BB", "Husbands"),
("BB-44", "BB", "Johns Plain"),
("BB-45", "BB", "Lancaster"),
("BB-46", "BB", "Mount Brevitor"),
("BB-47", "BB", "Mount Gay"),
("BB-48", "BB", "Newton Terrace"),
("BB-49", "BB", "Oughterson"),
("BB-50", "BB", "Pickerings");

-- Belarus

INSERT INTO countries VALUES 
("BY", "EU", "Belarus", "Minsk");

INSERT INTO states VALUES
("BY-HM", "BY", "Minsk Region"),
("BY-HO", "BY", "Homiel Region"),
("BY-BR", "BY", "Brest Region"),
("BY-HR", "BY", "Hrodna Region"),
("BY-MG", "BY", "Mahilyow Region"),
("BY-HL", "BY", "Homyel Region"),
("BY-MO", "BY", "Mogilev Region"),
("BY-GR", "BY", "Grodno Region"),
("BY-VI", "BY", "Vitebsk Region");


INSERT INTO cities VALUES
("BY-HR-G", "BY-HR", "Gomel"),
("BY-HR-M", "BY-HR", "Mazyr"),
("BY-HR-Z", "BY-HR", "Zhlobin"),
("BY-BR-B", "BY-BR", "Brest"),
("BY-BR-P", "BY-BR", "Pinsk"),
("BY-BR-K", "BY-BR", "Kobryn"),
("BY-MA-M", "BY-MA", "Mogilev"),
("BY-MA-B", "BY-MA", "Bobruisk"),
("BY-MA-O", "BY-MA", "Osipovichi"),
("BY-GR-G", "BY-GR", "Grodno"),
("BY-GR-L", "BY-GR", "Lida"),
("BY-GR-V", "BY-GR", "Volkovysk"),
("BY-VI-V", "BY-VI", "Vitebsk"),
("BY-VI-O", "BY-VI", "Orsha"),
("BY-VI-N", "BY-VI", "Novopolotsk"),
("BY-MI-M", "BY-MI", "Minsk"),
("BY-MI-SL", "BY-MI", "Slutsk"),
("BY-MI-B", "BY-MI", "Borisov"),
("BY-MI-Z", "BY-MI", "Zaslavl"),
("BY-HR-K", "BY-HR", "Kalinkovichi"),
("BY-HR-R", "BY-HR", "Rechitsa"),
("BY-HR-P", "BY-HR", "Pietrykaw"),
("BY-BR-L", "BY-BR", "Luninets"),
("BY-BR-M", "BY-BR", "Malaryta"),
("BY-BR-I", "BY-BR", "Ivatsevichy"),
("BY-MA-S", "BY-MA", "Shklow"),
("BY-MA-SL", "BY-MA", "Slavgorod"),
("BY-MA-K", "BY-MA", "Krichev"),
("BY-GR-S", "BY-GR", "Slonim"),
("BY-GR-I", "BY-GR", "Indura"),
("BY-GR-SK", "BY-GR", "Skidel"),
("BY-VI-N", "BY-VI", "Navapolatsk"),
("BY-VI-P", "BY-VI", "Polotsk"),
("BY-VI-NR", "BY-VI", "Novolukoml"),
("BY-MI-SM", "BY-MI", "Smolevichi"),
("BY-MI-MO", "BY-MI", "Molodechno"),
("BY-MI-ZH", "BY-MI", "Zhodino"),
("BY-MI-MO", "BY-MI", "Molodechno");


-- belgium


INSERT INTO countries VALUES 
("BE", "EU", "Belgium", "Brussels");

INSERT INTO states VALUES
("BE-BRU", "BE", "Brussels-Capital Region"),
("BE-VLG", "BE", "Flemish Region"),
("BE-WAL", "BE", "Walloon Region"),
("BE-BRU", "BE", "Brussels-Capital Region"),
("BE-VLG", "BE", "Flemish Region"),
("BE-WAL", "BE", "Walloon Region"),
("BE-VLG-AN", "BE-VLG", "Antwerp"),
("BE-VLG-LI", "BE-VLG", "Limburg"),
("BE-VLG-OV", "BE-VLG", "East Flanders"),
("BE-VLG-WV", "BE-VLG", "West Flanders"),
("BE-VLG-VB", "BE-VLG", "Flemish Brabant"),
("BE-WAL-WB", "BE-WAL", "Walloon Brabant"),
("BE-WAL-HA", "BE-WAL", "Hainaut"),
("BE-WAL-LG", "BE-WAL", "Liege"),
("BE-WAL-LX", "BE-WAL", "Luxembourg"),
("BE-WAL-NM", "BE-WAL", "Namur");

INSERT INTO cities VALUES
("BE-BRU-FR", "BE-BRU", "Forest"),
("BE-BRU-GA", "BE-BRU", "Ganshoren"),
("BE-BRU-JE", "BE-BRU", "Jette"),
("BE-BRU-KO", "BE-BRU", "Koekelberg"),
("BE-BRU-SC", "BE-BRU", "Sint-Agatha-Berchem"),
("BE-BRU-SA", "BE-BRU", "Sint-Jans-Molenbeek"),
("BE-BRU-SG", "BE-BRU", "Sint-Gillis"),
("BE-BRU-SJ", "BE-BRU", "Sint-Joost-ten-Node"),
("BE-BRU-SW", "BE-BRU", "Sint-Lambrechts-Woluwe"),
("BE-BRU-SM", "BE-BRU", "Sint-Pieters-Woluwe"),
("BE-BRU-UK", "BE-BRU", "Uccle"),
("BE-BRU-WA", "BE-BRU", "Watermael-Boitsfort"),
("BE-BRU-WE", "BE-BRU", "Woluwe-Saint-Étienne"),
("BE-BRU-WO", "BE-BRU", "Woluwe-Saint-Lambert"),
("BE-VLG-HE", "BE-VLG", "Herent"),
("BE-VLG-HO", "BE-VLG", "Hove"),
("BE-VLG-IW", "BE-VLG", "Izegem"),
("BE-VLG-JB", "BE-VLG", "Jabbeke"),
("BE-VLG-KO", "BE-VLG", "Koksijde"),
("BE-VLG-KO", "BE-VLG", "Kortrijk"),
("BE-VLG-LA", "BE-VLG", "Lanaken"),
("BE-VLG-LE", "BE-VLG", "Lennik"),
("BE-VLG-LI", "BE-VLG", "Lier"),
("BE-VLG-LK", "BE-VLG", "Lokeren"),
("BE-VLG-LM", "BE-VLG", "Lommel"),
("BE-VLG-LU", "BE-VLG", "Lummen"),
("BE-VLG-MA", "BE-VLG", "Machelen"),
("BE-VLG-MC", "BE-VLG", "Mechelen"),
("BE-VLG-ME", "BE-VLG", "Menen"),
("BE-VLG-MO", "BE-VLG", "Mol"),
("BE-VLG-NA", "BE-VLG", "Namen"),
("BE-VLG-NE", "BE-VLG", "Neerpelt"),
("BE-VLG-OO", "BE-VLG", "Oostende"),
("BE-VLG-OP", "BE-VLG", "Oudenaarde"),
("BE-VLG-RA", "BE-VLG", "Ranst"),
("BE-VLG-RE", "BE-VLG", "Retie"),
("BE-VLG-RH", "BE-VLG", "Riemst"),
("BE-VLG-RN", "BE-VLG", "Roeselare"),
("BE-VLG-RU", "BE-VLG", "Rumst"),
("BE-VLG-SE", "BE-VLG", "Scherpenheuvel-Zichem"),
("BE-VLG-SI", "BE-VLG", "Sint-Niklaas"),
("BE-VLG-SS", "BE-VLG", "Sint-Truiden"),
("BE-VLG-TO", "BE-VLG", "Tongeren"),
("BE-VLG-TU", "BE-VLG", "Turnhout"),
("BE-VLG-VI", "BE-VLG", "Vilvoorde"),
("BE-VLG-VR", "BE-VLG", "Vorselaar"),
("BE-VLG-WE", "BE-VLG", "Wellen"),
("BE-VLG-WI", "BE-VLG", "Willebroek"),
("BE-VLG-ZA", "BE-VLG", "Zaventem"),
("BE-VLG-ZO", "BE-VLG", "Zottegem"),
("BE-WAL-BI", "BE-WAL", "Binche"),
("BE-WAL-CA", "BE-WAL", "Chapelle-lez-Herlaimont"),
("BE-WAL-CO", "BE-WAL", "Comines-Warneton"),
("BE-WAL-EN", "BE-WAL", "Enghien"),
("BE-WAL-ER", "BE-WAL", "Erquelinnes"),
("BE-WAL-FA", "BE-WAL", "Farciennes"),
("BE-WAL-FL", "BE-WAL", "Flobecq"),
("BE-WAL-FR", "BE-WAL", "Frasnes-lez-Anvaing");

-- belize

INSERT INTO countries VALUES 
("BZ", "NA", "Belize", "Belmopan");

INSERT INTO states VALUES
("BZ-BZ", "BZ", "Belize District"),
("BZ-CY", "BZ", "Cayo District"),
("BZ-CZL", "BZ", "Corozal District"),
("BZ-OW", "BZ", "Orange Walk District"),
("BZ-SC", "BZ", "Stann Creek District"),
("BZ-TOL", "BZ", "Toledo District");

INSERT INTO cities VALUES
("BZ-BZ-B", "BZ-BZ", "Belize City"),
("BZ-BZ-S", "BZ-BZ", "San Pedro"),
("BZ-BZ-BL", "BZ-BZ", "Belmopan"),
("BZ-BZ-D", "BZ-BZ", "Dangriga"),
("BZ-BZ-H", "BZ-BZ", "Hattieville"),
("BZ-BZ-L", "BZ-BZ", "Ladyville"),
("BZ-BZ-P", "BZ-BZ", "Punta Gorda"),
("BZ-BZ-PG", "BZ-BZ", "Placencia"),
("BZ-BZ-SG", "BZ-BZ", "San Ignacio"),
("BZ-BZ-SL", "BZ-BZ", "San Pedro Columbia"),
("BZ-CY-B", "BZ-CY", "Belmopan"),
("BZ-CY-BE", "BZ-CY", "Benque Viejo del Carmen"),
("BZ-CY-BL", "BZ-CY", "Bullet Tree Falls"),
("BZ-CY-S", "BZ-CY", "San Ignacio"),
("BZ-CY-SB", "BZ-CY", "Santa Elena"),
("BZ-CY-SJ", "BZ-CY", "San Jose Succotz"),
("BZ-CY-T", "BZ-CY", "Teakettle"),
("BZ-CZL-C", "BZ-CZL", "Corozal Town"),
("BZ-CZL-CO", "BZ-CZL", "Corozalito"),
("BZ-CZL-LO", "BZ-CZL", "Louisville"),
("BZ-CZL-P", "BZ-CZL", "Progresso"),
("BZ-CZL-S", "BZ-CZL", "San Andres"),
("BZ-CZL-SJ", "BZ-CZL", "San Joaquin"),
("BZ-OW-C", "BZ-OW", "Orange Walk Town"),
("BZ-OW-D", "BZ-OW", "Douglas"),
("BZ-OW-YO", "BZ-OW", "Yo Creek"),
("BZ-OW-T", "BZ-OW", "Trial Farm"),
("BZ-SC-D", "BZ-SC", "Dangriga"),
("BZ-SC-H", "BZ-SC", "Hopkins"),
("BZ-SC-M", "BZ-SC", "Mango Creek"),
("BZ-SC-P", "BZ-SC", "Placencia"),
("BZ-TOL-B", "BZ-TOL", "Big Falls"),
("BZ-TOL-C", "BZ-TOL", "Crique Sarco"),
("BZ-TOL-D", "BZ-TOL", "Dolores"),
("BZ-TOL-E", "BZ-TOL", "Eldridgeville"),
("BZ-TOL-M", "BZ-TOL", "Mabilha"),
("BZ-TOL-P", "BZ-TOL", "Punta Gorda"),
("BZ-TOL-S", "BZ-TOL", "San Antonio");


